name: Repository Dispatch

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
    # only publish modules under packages
    paths:
      - "packages/**/*"

jobs:
  dispatch:
    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.LERNA_SANDBOX_OWNER }}
        repository: onursumer/dispatch-listener
        event-type: lerna-sandbox-package-update
