name: Repository Dispatch

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
    # only publish modules under packages
    paths:
      - "packages/**/*"

jobs:
  dispatch:
    if: github.repository == 'onursumer/lerna-sandbox' && github.actor != 'cbioportal-devops'
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.LERNA_SANDBOX_OWNER }}
          repository: onursumer/dispatch-listener
          event-type: some-random-event
