# Update package versions
name: Update Package Version

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
    # only publish modules under packages
    paths:
      - "packages/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=0 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v1
        with:
          node-version: '10.20.0'
      - run: yarn
      - run: yarn updateVersion
      - run: yarn publishModules
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}