on:
  push:
    branches:
      - production
name: "Semantic Release on Master"
jobs:
  publish:
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Ensure NPM access
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm i npm@8 -g # we need a version of npm that supports workspaces
      - run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: "${{ github.actor }}@users.noreply.github.com"
          GIT_COMMITTER_EMAIL: "${{ github.actor }}@users.noreply.github.com"
        run: lerna exec --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo
